spring:
  application:
    name: fitQuest
  datasource:
    url: jdbc:postgresql://localhost:5432/fitquest
    username: postgres
    password: shahbain
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
